version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: maxibor-gluetun_server_1
      APP_PORT: 7878
      PROXY_AUTH_WHITELIST: /api/*
      # Set false if another app from outside your umbrell wants to connect without login!
      PROXY_AUTH_ADD: 'false'

  server:
    image: linuxserver/radarr:6.0.4@sha256:06ac318ecb95a34c7b229568dcb4271f02cb5007bb189a0dd67a2032864187ca
    network_mode: "container:maxibor-gluetun_server_1"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
