services:
  app_proxy:
    environment:
      APP_HOST: maxibor-gluetun_server_1
      APP_PORT: 7878
      # Use this if another app outside your umbrel device wants to connect via an API call
      PROXY_AUTH_WHITELIST: /api/*
      # Set false if another app from outside your umbrell wants to connect without login!
      PROXY_AUTH_ADD: 'false'

  server:
    image: lscr.io/linuxserver/radarr:latest
    # Use Gluetun's network stack - all traffic goes through VPN
    network_mode: "container:maxibor-gluetun_server_1"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads/Films:/movies
      - ${UMBREL_ROOT}/home/Downloads/Films2:/movies2
      - ${UMBREL_ROOT}/home/Downloads/complete:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    stop_grace_period: 1m