services:
  app_proxy:
    environment:
      APP_HOST: maxibor-gluetun_server_1
      APP_PORT: 5055
      # Use this if another app outside your umbrel device wants to connect via an API call
      PROXY_AUTH_WHITELIST: /api/*
      # Set false if another app from outside your umbrell wants to connect without login!
      PROXY_AUTH_ADD: 'false'

  server:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    init: true
    network_mode: "container:maxibor-gluetun_server_1"
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Amsterdam
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped